export const SITE_CONFIG = {
  brandName: "Sanjay Web Agency",
  tagline: "Engineering Digital Experiences Built to Perform.",
  shortDescription: "We design and develop fast, scalable websites, SaaS platforms and custom web applications for startups and growing businesses.",
  longDescription: "Sanjay Web Agency is a full-stack web development studio specializing in Next.js, React, Node.js, and scalable web applications for startups and businesses.",
  domain: "https://sanjay.nirogplus.com",
  founder: {
    name: "Sanjay Gupta",
    role: "Lead Full-Stack Developer & Founder",
    bio: "Full-stack engineer building high-performance web applications, SaaS platforms, and modern digital products for startups & enterprises worldwide.",
    avatar: "/sanjay.jpg",
  },
  contact: {
    email: "guptaji30749@gmail.com",
    phone: "+91 8707375679",
    address: "India / Available Worldwide",
    availability: "Available for new projects",
  },
  social: {
    github: "https://github.com/sanjay9664?tab=repositories",
    linkedin: "https://www.linkedin.com/in/sanjay-gupta-53b677224/",
  },
  navigation: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Work", href: "/portfolio" },
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
  ],
  servicesSummary: [
    "Custom Web Development",
    "Next.js Development",
    "Full-Stack Development",
    "SaaS Development",
    "E-Commerce Development",
    "Dashboard & Admin Panel Development",
    "API Development & Integration",
    "Website Redesign & Performance Optimization",
  ],
  techStack: [
    "Next.js",
    "React",
    "TypeScript",
    "Node.js",
    "Express",
    "Laravel",
    "PHP",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Prisma",
    "Docker",
    "AWS",
    "Redis",
    "REST API",
    "GraphQL",
    "WebSockets",
    "Tailwind CSS",
  ],
  ctas: {
    primary: "Start Your Project",
    secondary: "View Our Work",
    conversion: "Let's Talk",
    schedule: "Schedule a Call",
  },
} as const;

export type SiteConfig = typeof SITE_CONFIG;
